name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/test

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - id: install-deps
        name: Install dependencies
        run: |
          bun install
      - id: test
        name: Run test
        run: |
          bun test
      - id: build
        name: Run build
        run: |
          bun install -g uglify-js shx
          bun run build
